### ISSUE TITLE
Home page: First Slider should show people hacking on hardware

### ISSUE THREAD

**Issue by turbosnail9** [wearhacks/main_wearhacks#7]

**Comment by nadbm** [comment]
Blocking: No proper picture for the slide. Someone needs to make a banner image.

**Comment by turbosnail9** [comment]
![image](https://cloud.githubusercontent.com/assets/1605925/11492361/38449b18-97ba-11e5-9664-33cdc6874599.png)

**Comment by turbosnail9** [comment]
![image3](https://cloud.githubusercontent.com/assets/1605925/11522522/d166c9f8-9885-11e5-953d-f61b71668cd4.png)
